# http://en.wikipedia.org/wiki/YAML
default: &common
  # Settings to configure the application details.
  app:
    name: My Application Name
  # Settings to configure Action Mailer.
  action_mailer:
    raise_delivery_errors: true
    delivery_method: smtp
    smtp_settings:
      address: mail.my_domain
      # Most used values for port : 26, 587, and 465
      port: 26
      domain: my_domain
      user_name: notifier@my_domain
      password: my_password
      # The valid values for this field are : :plain, :login, and :cram_md5
      authentication: plain
    default_url_options:
      host: my_host
  # Settings to configure the "authentication" gem "devise". Please refer to "config/initializers/devise.rb" for more details about the configuration variables and values.
  devise:
    mailer_sender: notifier@my_domain
    scoped_views: true
development:
  <<: *common
test:
  <<: *common
production:
  <<: *common