# http://en.wikipedia.org/wiki/YAML
default: &common
  # Settings to configure Action Mailer.
  action_mailer:
    raise_delivery_errors: true
    delivery_method: smtp
    smtp_settings:
      address: mail.my_domain
      # Most used values for port : 26, 587, and 465
      port: 26
      domain: my_domain
      user_name: notifier@my_domain
      password: my_password
      # The valid values for this field are : :plain, :login, and :cram_md5
      authentication: plain
    default_url_options:
      host: my_host
  # Settings to configure Exception Notification.
  exception_notification:
    email_prefix: email_prefix
    # There is a bug in the "smtp.rb" file in Ruby 1.8.7 and we cannot do this : "'Notifier' <notifier@my_domain>" so we have just to do this : "notifier@my_domain"
    sender_address: notifier@my_domain
    exception_recipients: exception_recipients
  # Settings to configure the "authentication" gem "devise". Please refer to "config/initializers/devise.rb" for more details about the configuration variables and values.
  devise:
    mailer_sender: notifier@my_domain
development:
  <<: *common
test:
  <<: *common
production:
  <<: *common